name: wif_workaround
description: |
  A workaround to use Workload Identity Federation with googleapis_auth,
  calls gcloud CLI to get the access token.
repository: https://github.com/alexeyinkin/dart-wif-workaround

version: 0.1.1

environment:
  sdk: ^3.0.0

dependencies:
  googleapis_auth: ^1.4.0
  http: ^1.0.0

dev_dependencies:
  total_lints: ^3.2.0
